### ISSUE TITLE
DEPLOYMENT_DISABLED

### ISSUE THREAD

**Issue by unclebay143** [sadmann7/netflx-web#1]
Getting this error on the plans page
![image](https://user-images.githubusercontent.com/58919619/234478916-b505c02c-1ad6-448a-9b2a-fd5a119372f7.png)

**Comment by sadmann7** [comment]
Check if you have configured the stripe envs properly. You need to run: yarn run stripe:listen. This will listen for stripe events locally

**Comment by sadmann7** [comment]
Vercel have disabled the deployment because of the exceeding limit of the hobby tier

**Comment by unclebay143** [comment]
> Vercel have disabled the deployment because of the exceeding limit of the hobby tier

Sorry to hear about that. Can you share more details about what's exceeded?

**Comment by sadmann7** [comment]
the image optimization for next/image
