### ISSUE TITLE
How to add Movies/Shows

### ISSUE THREAD

**Issue by jontstaz** [sadmann7/netflx-web#3]
Nice script! I can't see how you're meant to actually add full movies/TV shows? I only see trailer functionality from my initial glance. What's the process for uploading files and/or embedding external streaming links?

**Comment by sadmann7** [comment]
I am using the tmdb api. It doesn't offer any videos other than trailers, and scenes. You add a video field on the MyShow prisma model, and upload your own shows with video and stuffs.
