### ISSUE TITLE
An error is reported after startup

### ISSUE THREAD

**Issue by shnehna** [sadmann7/netflx-web#6]
I didn't change any settings.Just 'yarn run dev'.

<img width="1190" alt="image" src="https://github.com/sadmann7/netflx-web/assets/34475035/3cc27f69-d8cb-47a3-81b4-0cae00bc60d0">
<img width="1680" alt="image" src="https://github.com/sadmann7/netflx-web/assets/34475035/bd6c7d5b-b66c-4538-924d-da63ca4f189a">
<img width="958" alt="image" src="https://github.com/sadmann7/netflx-web/assets/34475035/fe27eac9-02af-43de-b077-f3e717ccc009">

**Comment by zKkk02** [comment]
Have you solved your problem？

**Comment by zKkk02** [comment]
Have you solved your problem？
